Programs/beep_solaris.c needs to include "log.h"
Fixes build errors on Solaris of:

./beep_solaris.c:31:7: warning: implicit declaration of function ‘logMessage’ [-Wimplicit-function-declaration]
       logMessage(LOG_DEBUG, "keyboard opened: fd=%d", keyboard);
       ^
./beep_solaris.c:31:18: error: ‘LOG_DEBUG’ undeclared (first use in this function)
       logMessage(LOG_DEBUG, "keyboard opened: fd=%d", keyboard);
                  ^
./beep_solaris.c:33:7: warning: implicit declaration of function ‘logSystemError’ [-Wimplicit-function-declaration]
       logSystemError("keyboard open");
       ^

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>