Add #includes needed to build beep_solaris.c & pcm_audio.c on Solaris
Fixes build errors on Solaris of:

./beep_solaris.c: In function 'getKeyboard':
./beep_solaris.c:30:21: warning: implicit declaration of
  function 'open' [-Wimplicit-function-declaration]
     if ((keyboard = open("/dev/kbd", O_WRONLY)) != -1) {
                     ^
./beep_solaris.c:30:38: error: 'O_WRONLY' undeclared
  (first use in this function)
     if ((keyboard = open("/dev/kbd", O_WRONLY)) != -1) {
                                      ^

./pcm_audio.c: In function 'openPcmDevice':
./pcm_audio.c:40:32: warning: implicit declaration of
  function 'open' [-Wimplicit-function-declaration]
     if ((pcm->fileDescriptor = open(device, O_WRONLY|O_NONBLOCK)) != -1) {
                                ^
./pcm_audio.c:40:45: error: 'O_WRONLY' undeclared
  (first use in this function)
     if ((pcm->fileDescriptor = open(device, O_WRONLY|O_NONBLOCK)) != -1) {

./pcm_audio.c:40:54: error: 'O_NONBLOCK' undeclared
  (first use in this function)
     if ((pcm->fileDescriptor = open(device, O_WRONLY|O_NONBLOCK)) != -1) {
                                                      ^
./pcm_audio.c:56:61: warning: implicit declaration of
  function 'strerror' [-Wimplicit-function-declaration]
         logMessage(errorLevel, "Cannot set audio info: %s", strerror(errno));
                                                             ^
./pcm_audio.c:56:70: error: 'errno' undeclared
  (first use in this function)
         logMessage(errorLevel, "Cannot set audio info: %s", strerror(errno));
                                                                      ^