Handle OCaml safe-string
Since OCaml 4.10 strings are immutable by default.

This affects the String_val() API, which returns a 'const char *'.
This affects the caml_named_value() API, which returns a 'const char *'.

Add backward compatible change to handle -safe-string and -unsafe-string.

ocamlc.opt -ccopt "-I. -I. -I./../../Programs -I../../Programs -I../../Headers -I./../.. -I../..  -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux  -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=2 -D_BSD_SOURCE -D_XOPEN_SOURCE=500 -D_XOPEN_SOURCE_EXTENDED -D_GNU_SOURCE -DHAVE_CONFIG_H -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -std=gnu99 -Wall -Werror=format-security" -I ./../../Programs -I ../../Programs -c ./brlapi_stubs.c
./brlapi_stubs.c: In function 'raise_brlapi_error':
./brlapi_stubs.c:150:34: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  150 |   if (exception==NULL) exception = caml_named_value("Brlapi_error");
      |                                  ^
./brlapi_stubs.c: In function 'raise_brlapi_exception':
./brlapi_stubs.c:168:34: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  168 |   if (exception==NULL) exception = caml_named_value("Brlapi_exception");
      |                                  ^
./brlapi_stubs.c: In function 'brlapiml_write':
./brlapi_stubs.c:312:11: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  312 |   wa.text = String_val(Field(writeArguments, 3));
      |           ^
./brlapi_stubs.c:318:14: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  318 |   wa.charset = String_val(Field(writeArguments, 7));
      |              ^
cc1: some warnings being treated as errors
make[2]: *** [Makefile:104: brlapi_stubs.o] Error 2

Signed-off-by: Olaf Hering <olaf@aepfle.de>