check for functions inb & outb
Musl C library provides sys/io.h but inb and outb are missing on some
archs. This patch adds a configure check ported from sane-backends:
https://github.com/solanoalves/sane-backend/blob/059b97962ecb1b1ab068f524988d16c5b55bbd29/configure.ac#L314
to fix build errors detected by buildroot autobuilders:
https://autobuild.buildroot.net/results/76d/76d18437241d1281566b76ed1cec2ba99c3532da//build-end.log

./ports_glibc.c: In function 'readPort1':
./ports_glibc.c:54:10: error: implicit declaration of function 'inb' [-Wimplicit-function-declaration]
   54 |   return inb(port);
      |          ^~~
./ports_glibc.c: In function 'writePort1':
./ports_glibc.c:63:3: error: implicit declaration of function 'outb' [-Wimplicit-function-declaration]
   63 |   outb(value, port);
      |   ^~~~

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>