Fix builds on Solaris 10 & 11 to work with -std=gnu99
Solaris 10 & 11 system headers require that if a C99 compiler is used
and _XOPEN_SOURCE is specified, that _XOPEN_SOURCE must be 600, since
prior versions of the X/Open standards only supported C89.

Fixes many errors in configure and build steps of:
/usr/include/sys/feature_tests.h:397:2: error: #error "Compiler or options
 invalid for pre-UNIX 03 X/Open applications  and pre-2001 POSIX applications"

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>